# Generated by Django 4.2.1 on 2023-05-31 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0002_auto_20230520_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='image',
            field=models.ImageField(null=True, upload_to='imagen_principal'),
        ),
        migrations.CreateModel(
            name='caracteristicas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caracteristica', models.CharField(max_length=200)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caracteristicas', to='vehiculos.vehiculo')),
            ],
        ),
    ]
