# Generated by Django 4.2.1 on 2023-05-31 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0003_vehiculo_image_caracteristicas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caracteristicas',
            name='caracteristica',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
