# Generated by Django 4.2.1 on 2023-05-31 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0004_alter_caracteristicas_caracteristica'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiculo',
            old_name='image',
            new_name='imagen_principal',
        ),
    ]
