# Generated by Django 4.2.1 on 2023-06-24 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0007_team_imageurl_team_linkedinurl_team_name_team_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='role',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
